apiVersion: apps/v1
kind: Deployment
metadata:
  name: mugang-frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/mugang-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # 외부 사용자가 홈페이지에 접속할 수 있도록 ALB/NLB 생성 옵션
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
